
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/router.dart';
import 'firebase_options.dart'; // This will be generated by the user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  print('DEBUG: Starting Firebase initialization...');
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('DEBUG: Firebase initialized successfully!');
  } catch (e, st) {
    print('DEBUG: Firebase initialization FAILED: $e');
    print(st);
  }
  
  runApp(const ProviderScope(child: PickEatPickItApp()));
}

class PickEatPickItApp extends ConsumerWidget {
  const PickEatPickItApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'PickEat PickIt',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: router,
    );
  }
}
